version: "3.1"
services:
  todolist:
    container_name: todolist
    image: todolist
    build: .
    env_file: .env
    command: sh -c "flask db upgrade && gunicorn todolist:app -w 2 -b :8000"
    volumes:
      - /data/flask-todolist/todolist.db:/code/todolist.db
    ports:
      - "30010:8000"
