# Use root/example as user/password credentials
version: '3.1'

services:
  home-docsify:
    image: swr.cn-north-4.myhuaweicloud.com/hw_008618613073290_01/home-docsify:1.0
    restart: always
    ports:
      - 30300:3000
    volumes:
      - /docs:/docs