# Use root/example as user/password credentials
version: '3.1'

services:
  nginx-mb:
    image: swr.cn-south-1.myhuaweicloud.com/mangoorg/docker-mb:1.5
    restart: always
    ports:
      - 30380:80
    volumes:
      - /data:/data