apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}
spec:
  selector:
    app: {{.Values.app.name}}
  type: NodePort
  ports:
  - protocol: TCP
    port: {{.Values.app.targetPort}}
    targetPort: {{.Values.app.targetPort}}
    nodePort: {{.Values.app.nodePort}}
