apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-pv
  namespace: {{.Values.namespace}}
  labels:
    type: home-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /docs
