apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-pvc
  namespace: {{.Values.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: home-pv