apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: {{.Values.namespace}}
  labels:
    type: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mysqldata
