# Use root/example as user/password credentials
version: '3.1'

services:
  flask-api:
    image: swr.cn-south-1.myhuaweicloud.com/mangoorg/flask-api:1.0-20211106
    restart: always
    ports:
      - 30704:7004
    environment:
      REDIS_HOST: hw.meiflower.top
      REDIS_PORT: 30379
      REDIS_PWD: Mg19930324@