apiVersion: v1
kind: PersistentVolume
metadata:
  name: mb3-pv
  namespace: {{.Values.namespace}}
  labels:
    type: mb3-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data
