apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mb3-pvc
  namespace: {{.Values.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: mb3-pv