apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}
  namespace: {{.Values.namespace}}
  labels:
    name: {{.Values.app.name}}
spec:
  type: NodePort
  ports:
    - port: {{.Values.app.targetPort}}
      targetPort: {{.Values.app.targetPort}}
      protocol: TCP
      nodePort: {{.Values.app.nodePort}}
  selector:
    app: {{.Values.app.name}}