apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  namespace: {{.Values.namespace}}
  labels:
    type: es-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /esdata
