apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: {{.Values.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: es-pv