version: '3.1'
services:
  zoo1:
    image: zookeeper:3.6
    environment:
      TZ: Asia/Shanghai
      ZOO_DATA_LOG_DIR: /data
      # ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,wchs,cons,conf,stat,crst
      ZOO_4LW_COMMANDS_WHITELIST: '*'
      JMXPORT: 21811
    restart: always
    ports:
      - 2181:2181
      - 8080:8080
      - 21811:21811