version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 28080:80

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example