# Use root/example as user/password credentials
version: '3.1'

services:
  kiftd:
    image: swr.cn-south-1.myhuaweicloud.com/mangoorg/kiftd:1.0.35
    restart: always
    ports:
      - 30480:8080
    volumes:
      - /data/kiftd/filesystem:/opt/kiftd/filesystem
      - /data/kiftd/conf:/opt/kiftd/conf