# 命名空间
namespace: default
# 应用相关
app:
  # 应用名称
  name: flask-api
  # 应用副本数
  replicas: 1
  # 应用镜像
  image: mangomei/flask-api:1.0-20211106
  # 容器端口
  targetPort: 7004
  # svc端口
  nodePort: 30002
  env:
    # redis配置
    redisHost: 10.0.16.8
    redisPort: 30379
    redisPwd: Mg19930324@