apiVersion: batch/v1
kind: CronJob
metadata:
  name: card-cronjob
  namespace: {{.Values.namespace}}
spec:
  schedule: {{.Values.app.emailBackCron}}
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          nodeName: master
          containers:
          - name: card-cronjob
            image: python:3.6.14-alpine
            command: ["python3", "email_back.py"]
            workingDir: /opt
            volumeMounts:
            - name: card-v
              mountPath: /opt
          volumes:
          - name: card-v
            hostPath:
              path: /nfsdata/sqlite