apiVersion: v1
kind: PersistentVolume
metadata:
  name: card-pv
  namespace: {{.Values.namespace}}
  labels:
    type: card-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /nfsdata
