# 命名空间
namespace: default
# 应用相关
app:
  # 应用名称
  name: card-api
  # 应用副本数
  replicas: 1
  # 应用镜像
  image: mangomei/card:3.1-20211107
  env:
    # 应用配置
    config: /opt/config/application.properties
    # jvm 参数
    javaOpts:
  # 容器端口
  targetPort: 9001
  # svc端口
  nodePort: 30901
  # 每天中午12点备份，容器内时间 +8 小时
  #emailBackCron: "0 4 * * *"
  emailBackCron: "0/10 * * * *"