# 命名空间
namespace: default
# 应用相关
app:
  # 应用名称
  name: card-api
  # 应用副本数
  replicas: 1
  # 应用镜像
  image: mangomei/card:latest
  env:
    # 应用配置
    config: /opt/config/application.properties
    # jvm 参数
    #javaOpts: "-Xms200m -Xmx200m -Xmn120m -XX:MetaspaceSize=80m -XX:MaxMetaspaceSize=200m -Xverify:none -XX:+UseG1GC"
    javaOpts:
  # 容器端口
  targetPort: 9001
  # svc端口
  nodePort: 30901
  # 每天中午12点备份，容器内时间 +8 小时
  emailBackCron: "0 4 * * *"
  #emailBackCron: "0/1 * * * *"